image: archlinux
packages:
  - rust
  - cargo-deny
  - unshield
sources:
  - https://git.sr.ht/~redstrate/libphysis
tasks:
  - reuse: |
      cd libphysis
      reuse lint
  - check: |
      cd libphysis
      cargo check
  - deny-check: |
      cd libphysis
      cargo deny check