[advisories]
version = 2

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "GPL-3.0",
    "MPL-2.0",
    "Unicode-3.0", # used for unicode-ident
    "Zlib"
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/redstrate/physis", "https://github.com/redstrate/miscel"]
